version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      PORT: 3000
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: mydb
      PGPORT: 5432
    ports:
      - "3000:3000"

volumes:
  pgdata:
