services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./db/init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    ports:
      - "5434:5432"


volumes:
  pgdata:

